tasks:
    - name: Install Deno
      init: curl -fsSL https://deno.land/install.sh | sh
      command: |
        export DENO_INSTALL="/home/gitpod/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
